### ISSUE TITLE
libre-wsdl4j is not published to Maven Central

### ISSUE THREAD

**Issue by garydgregory** [librewsdl4j/libre-wsdl4j#18]
Would you please publish releases to Maven Central?

**Comment by andreasrosdal** [comment]
The process has started!  https://issues.sonatype.org/browse/OSSRH-88180

**Comment by andreasrosdal** [comment]
Request here: https://issues.sonatype.org/browse/OSSRH-88181

**Comment by andreasrosdal** [comment]
https://issues.sonatype.org/browse/OSSRH-88181

**Comment by andreasrosdal** [comment]
io.github.librewsdl4j available on Maven central now!

```xml

<dependency>
  <groupId>io.github.librewsdl4j</groupId>
  <artifactId>libre-wsdl4j</artifactId>
  <version>1.10.0</version>
</dependency> 
```

**Comment by garydgregory** [comment]
Thank you!
