### ISSUE TITLE
Track significant changes in a file

### ISSUE THREAD

**Issue by garydgregory** [librewsdl4j/libre-wsdl4j#41]
How should we track significant changes?

Simply, in a historical `RELEASE-NOTES.txt` file.

Or, using a Maven `src/changes/changes.xml` file, which can be used to generate release notes (a la Maven)?

**Comment by andreasrosdal** [comment]
https://github.com/librewsdl4j/libre-wsdl4j/releases/tag/1.10.0

We make release notes on GitHub.

**Comment by garydgregory** [comment]
Hi @andreasrosdal 
How do I know what's been done since the previous release? Looking at the git history is not so nice IMO since it's a mix of changes users care about, don't, or shouldn't.

**Comment by andreasrosdal** [comment]
You may volunteer to maintain such release notes in a text file, or sponsor this project with real funds. Otherwise this will most likely not change.

**Comment by garydgregory** [comment]
I can volunteer to update a file when _I_  push a change set or merge a PR, but if no one else does, that would only end up as misleading. I'm not sure where to go from here.

**Comment by andreasrosdal** [comment]
We can use the discussions section of this project to discuss how to improve the development and documentation process of  libre-wsdl4j:
https://github.com/librewsdl4j/libre-wsdl4j/discussions

Developers who are interested may volunteer to improve way this project is developed. 

At this point in time, I am maintaining libre-wsdl4j by merging dependency updates from dependabot, merging bugfixes if there would be any, and updating to prepare for new Java versions. So there is not so much going on here, and not really any significant changes. 

This is a volunteer effort to maintain the wsdl4j source code. The code is possibly in use in some enterprise businesses still, such as the company where I work. So if you have specific requirements, you may describe these here, and we can see how I may help with these.
