### ISSUE TITLE
When Final version release.

### ISSUE THREAD

**Issue by rsearls** [librewsdl4j/libre-wsdl4j#6]
This looks like a very good alternative to wsdl4j. 
When will a Final version be released and uploaded to a public repo (maven central)?

It would be very helpful moving forward if there was also a jakarta (API) version of this.
Thus maintaining separate and parallel versions.   If I submitted a PR for the jakarta changes
would you support it?
email (rsearls@redhat.com).

**Comment by andreasrosdal** [comment]
Thanks. Are you interested in helping with maintaining this library?

**Comment by rsearls** [comment]
I can't commit to full time help but I am will to submit a working PR and work through any issues it has.

**Comment by andreasrosdal** [comment]
You have commit access now. Please make this library magnificent.

**Comment by rsearls** [comment]
I propose restructuring the project to have 2 modules.  Module wsdl4j will
have all the original code. Module wsdl4j-jakarta will have the jakarta
package
name changes.  The archive names will be librewsdl4j:libre-wsdl4j and
librewsdl4j:libre-wsdl4j-jakarta.

Does this sound ok to you?

**Comment by andreasrosdal** [comment]
Yes, perfect.

**Comment by andreasrosdal** [comment]
Release 1.8.0 can be downloaded here:
https://github.com/librewsdl4j/libre-wsdl4j/releases/tag/1.8.0

**Comment by andreasrosdal** [comment]
Can you please try this?

https://github.com/librewsdl4j/libre-wsdl4j/packages/1002529
